apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-webhook-tls
type: Opaque
data:
  ca.crt: {{.Values.tls.caCert}}
  tls.crt: {{.Values.tls.clientCert}}
  tls.key: {{.Values.tls.clientKey}}

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.Release.Name}}-webhook
webhooks:
  {{- range $moduleName, $module := fromYaml .Values.modules }}
  - name: {{$moduleName}}.operator.kyma-project.io
  {{- if $module.labels }}
    objectSelector:
      matchLabels:
        {{ $module.labels | toYaml }}
  {{- end }}
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{.Values.tls.clientCert}}
      service:
        name: {{$.Release.Name}}-webhook
        namespace: {{$.Release.Namespace}}
        path: /validate/{{$moduleName}}
    rules:
      - apiGroups:
          - "operator.kyma-project.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
        {{- if not $module.statusOnly }}
          - "*"
        {{- else }}
          - "*/status"
        {{- end }}
    sideEffects: NoneOnDryRun
    timeoutSeconds: 15
    failurePolicy: Ignore
  {{- end }}
