---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skr-webhook-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-reader
rules:
- apiGroups: ["operator.kyma-project.io"] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-kymas
subjects:
- kind: ServiceAccount
  name: skr-webhook-sa
roleRef:
  kind: ClusterRole 
  name: kyma-reader 
  apiGroup: rbac.authorization.k8s.io
---