version: "2"
linters:
  default: all
  disable:
    - contextcheck # too many false positives
    - depguard # checks if package imports are whitelisted
    - exhaustruct # too subjective and harms code readability
    - nlreturn # too strict and mostly code is not more readable
    - paralleltest # should be enabled consciously for long running tests
    - lll # revive.line-length-limit serve same purpose
    - sqlclosecheck # not needed for this project
    - wsl # too strict and mostly code is not more readable
    - wsl_v5 # too strict
    - noinlineerr # we want to keep inlining
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 80
      statements: 60
    revive:
      severity: error
      rules:
        - name: comment-spacings
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - lll
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
