apiVersion: component.kyma-project.io/v1alpha1
kind: Watcher
metadata:
  name: watcher-kyma-sample
  labels:
    operator.kyma-project.io/default: "true"
spec:
  contractVersion: "1"
  componentName: "kyma"
  serviceInfo:
    servicePort: 8082
    serviceName: "kyma-event-service"
  gvrsToWatch:
  - gvr:
      group: "operator.kyma-project.io"
      version: "v1alpha1"
      resource: "kymas"
