linters:
  enable-all: true
  disable:
    - contextcheck # too many false positives
    - depguard # requires whitelisting imported pkgs
    - exhaustruct # TODO enable and fix, use regex to exclude certain cases
    - exportloopref # deprecated (since v1.60.2), replaced by copyloopvar
    - gci # keep disabled for now since it will autofix all imports and result in a git dirty state
    - godox # TODO enable and fix
    - err113 # too strict
    - gomnd # deprecated (since v1.58.0), renamed to mnd
    - ireturn # TODO enable and fix
    - musttag # deprecated
    - nlreturn # too strict and mostly code is not more readable
    - noctx # TODO enable and fix
    - rowserrcheck # deprecated
    - sqlclosecheck # not needed for this project
    - wastedassign # deprecated
    - wsl # too strict and mostly code is not more readable
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kyma-project)
  cyclop:
    max-complexity: 20
  funlen:
    statements: 60
    lines: 80
  revive:
    severity: error
    rules:
      - name: comment-spacings
        disabled: true
      - name: dot-imports
        severity: warning
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [ 120 ]
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - funlen
        - gochecknoglobals
        - lll
        - wrapcheck
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true
run:
  timeout: 5m
