version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - err113
    - exhaustruct
    - godox
    - ireturn
    - musttag
    - nlreturn
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - wsl
    - wsl_v5 # needs to be discussed with the team if enforced grouping of statements is desired, but generally too strict
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 80
      statements: 60
    revive:
      severity: error
      rules:
        - name: comment-spacings
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - lll
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
