linters:
  enable-all: true
  disable:
    - contextcheck # too many false positives
    - deadcode # deprecated (since v1.49.0) and replaced by 'unused'
    - depguard # requires whitelisting imported pkgs
    - exhaustivestruct # deprecated (since v1.46.0) and replaced by 'exhaustruct'
    - exhaustruct # TODO enable and fix, use regex to exclude certain cases
    - gci # keep disabled for now since it will autofix all imports and result in a git dirty state
    - godox # TODO enable and fix
    - goerr113 # too strict
    - golint # deprecated (since v1.41.0) and replaced by 'revive'
    - ifshort # deprecated (since v1.48.0)
    - interfacer # deprecated (since v1.38.0)
    - ireturn # TODO enable and fix
    - maligned # deprecated (since v1.38.0)
    - musttag # deprecated
    - nlreturn # too strict and mostly code is not more readable
    - noctx # TODO enable and fix
    - nosnakecase  # deprecated (since v1.48.1) and replaced by 'revive'
    - rowserrcheck # deprecated
    - scopelint # deprecated (since v1.39.0) and replaced by 'exportloopref'
    - structcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - sqlclosecheck # not needed for this project
    - varcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - wastedassign # deprecated
    - wsl # too strict and mostly code is not more readable
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kyma-project)
  cyclop:
    max-complexity: 20
  funlen:
    statements: 60
    lines: 80
  revive:
    severity: error
    rules:
      - name: comment-spacings
        disabled: true
      - name: dot-imports
        severity: warning
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [ 120 ]
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - funlen
        - gochecknoglobals
        - lll
        - wrapcheck
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true
run:
  timeout: 5m
