kind: ConfigMap
apiVersion: v1
metadata:
  name: kcp-watcher-modules
  labels:
    operator.kyma-project.io/controller-name: runtime-watcher
data:
  example-module-name-stable: |
    {
      "KymaCRList": [{
        "KymaCR": "abc",
        "KymaNamespace": "default"
      }, {
        "KymaCR": "def",
        "KymaNamespace": "default"
      }]
    }
