apiVersion: v1
stringData:
  gvrToWatch: '{
   "gvrList":[
      {
         "group":"operator.kyma-project.io",
         "version":"v1alpha1",
         "resource":"kymas",
         "labelValueList":[
            {
               "label":"operator.kyma-project.io/controller-name",
               "value":"kyma"
            }
         ]
      },
      {
         "group":"",
         "version":"v1",
         "resource":"configmaps",
         "labelValueList":[
            {
               "label":"operator.kyma-project.io/controller-name",
               "value":"kyma"
            }
         ]
      }
   ]
}'
kind: Secret
metadata:
  labels:
    operator.kyma-project.io/task-name: "label-watching"
  name: sample-secret
  namespace: operator-system
type: Opaque