name: Patch lifecycle-manager
description: Patches lifecycle-manager to use the PR specific watcher image.
inputs:
  runtime-watcher-tag:
    description: Tag of runtime-watcher to use
    required: true
  runtime-watcher-image-registry:
    description: Registry of runtime-watcher to use
    required: true
runs:
  using: composite
  steps:
    - name: Patch lifecycle-manager
      working-directory: lifecycle-manager
      shell: bash
      run: |
        pushd config/watcher_local_test
        echo \
        "- op: add
          path: /spec/template/spec/containers/0/args/-
          value: --skr-watcher-image-registry=${{.inputs.runtime-watcher-image-registry }}
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --skr-watcher-image-tag=${{ inputs.runtime-watcher-tag }}
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --oci-registry-host=http://not.relevant.for.our.tests" >> patch_watcher_img.yaml
        kustomize edit add patch --path patch_watcher_img.yaml --kind Deployment
        popd
        kustomize build config/watcher_local_test
