apiVersion: v1
kind: Service
metadata:
  name: skr-webhook
  namespace: default
spec:
  selector:
    #selector for deployment labels (key, values)
    app: skr-webhook
  ports:
    - port: {{.Values.service.port}}
      targetPort: watcher-port
      name: webhook

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skr-webhook
  namespace: default
  labels:
    app: skr-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skr-webhook
  template:
    metadata:
      labels:
        app: skr-webhook
    spec:
      containers:
        {{- if eq .Values.sidecar true }}
        - name: request-sidecar
          image: alpine
          command:
            - /bin/sh
            - "-c"
            - "sleep 60m"
          imagePullPolicy: Always
          volumeMounts:
            - name: request
              mountPath: /tmp
        {{- end }}
        - name: server
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WEBHOOK_PORT
              value: "{{.Values.service.targetPort}}"
            - name: TLS_ENABLED
              value: "true"
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: skr-webhook-tls
                  key: tls.key
            - name: TLS_CERT
              valueFrom:
                secretKeyRef:
                  name: skr-webhook-tls
                  key: tls.crt
            - name: KCP_IP
              value: "{{.Values.kcp.loadbalancerIP}}"
            - name: KCP_PORT
              value: "{{.Values.kcp.loadbalancerPort}}"
            - name: KCP_CONTRACT
              value: {{.Values.service.contactVersion}}
            - name: WEBHOOK_SIDE_CAR
              value: {{ if eq .Values.sidecar true }} "true" {{ else }} "false" {{ end }}
          image: "{{.Values.image.repository}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "800m"
          ports:
            - containerPort: {{.Values.service.targetPort}}
              name: watcher-port