apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-webhook-tls
type: Opaque
data:
  {{- $data := (lookup "v1" "Secret" .Release.Namespace (printf "%s-webhook-tls" .Release.Name )).data }}
  {{- $caCert := "" }}
  {{- if $data }}
  {{ $data | toYaml | nindent 2 }}
  {{- $caCert = index $data "ca.crt" }}
  {{- else }}
  {{- $cn := printf "%s-webhook.%s.svc" .Release.Name .Release.Namespace }}
  {{- $ca := genCA (printf "%s-webhook-ca" .Release.Name  ) 36500 }}
  {{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn "localhost") 36500 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- $caCert = $ca.Cert | b64enc }}
  {{- end }}

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: skr-webhook
webhooks:
  - name: label.operator.kyma-project.io
    objectSelector:
      matchLabels:
        app: kyma
    admissionReviewVersions:
      - v1
    clientConfig:
      # ca bundle should be filled from deployment
      caBundle:
      service:
        name: skr-webhook
        namespace: default
        path: /validate
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*"
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30
    failurePolicy: Fail
  - name: gvr.operator.kyma-project.io
    admissionReviewVersions:
      - v1
    clientConfig:
      # ca bundle should be filled from deployment
      caBundle: {{ $caCert }}
      service:
        name: skr-webhook
        namespace: default
        path: /validate
    rules:
      - apiGroups:
          - operator.kyma-project.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - kymas
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30
    failurePolicy: Fail