# -- Side car to mount admission review
sidecar: false
# -- Replicas
replicas: 1
image:
  # -- Image repository
  repository: aditya
  # -- Image tag
  tag: ""
  # -- Image pull policy
  pullPolicy: ""
# -- Image pull secrets
imagePullSecrets: []
# -- Pod security content
podSecurityContext: {}
# -- Node selector
nodeSelector: {}
# -- Affinity settings
affinity: {}
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 200Mi
    # -- CPU limit
    cpu: 0.1
  requests:
    # -- Memory request
    memory: 20Mi
    # -- CPU request
    cpu: 0.01
# -- Service port
service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 443
  # -- Target port
  targetPort: 8443
  # -- Target port
  contactVersion: 8443