{{- if not .Values.isWebhookConfigRendered }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: skr-webhook
webhooks:
  - name: label.operator.kyma-project.io
    objectSelector:
      matchLabels:
        app: kyma
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .CaCert }}
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /validate
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*"
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30
    failurePolicy: Fail
  - name: gvr.operator.kyma-project.io
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .CaCert }}
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /validate
    rules:
      - apiGroups:
          - operator.kyma-project.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - kymas
    sideEffects: NoneOnDryRun
    timeoutSeconds: 30
    failurePolicy: Fail
{{ end }}