apiVersion: component.kyma-project.io/v1alpha1
kind: Manifest
metadata:
  labels:
    operator.kyma-project.io/channel: stable
    operator.kyma-project.io/controller-name: manifest
    operator.kyma-project.io/kyma-name: kyma-sample
  name: manifestkyma-sample
  namespace: default
spec:
  config:
    ref: sha256:f5fe1c6ea10c69ecce18258b69657e3774616e1a8cc795df4a2f7f85218e8f78
    name: kyma-project.io/module/kyma-watcher/operator
    repo: k3d-registry.localhost:4000/component-descriptors
    type: oci-ref
  installs:
    - source:
        name: kyma-project.io/module/kyma-watcher/operator
        repo: k3d-registry.localhost:4000/component-descriptors
        ref: sha256:11e1a109c8cce27e144bafd4c384cc29db8d518f2f404e427dc04ab12f5dae48
        type: oci-ref
      name: watcher-chart
