# permissions for end users to view watchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher-viewer-role
rules:
- apiGroups:
  - component.kyma-project.io
  resources:
  - watchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - component.kyma-project.io
  resources:
  - watchers/status
  verbs:
  - get
