name: "Test Changelog"

env:
  IMAGE_REPO: europe-docker.pkg.dev/kyma-project/prod/runtime-watcher-skr
  CODE_REPOSITORY: kyma-project/runtime-watcher

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/release/create_changelog.sh 1.1.4 ${{ env.IMAGE_REPO }}:1.1.4