name: Lint PR Title
run-name: ${{github.event.pull_request.title}}

permissions: { }

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check:
    name: Check Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            deps
            docs
            feat
            fix
            refactor
            test
          requireScope: false
          # https://regex101.com/r/YybDgS/1
          subjectPattern: ^([A-Z].*[^.]|bump .*)$
