name: TestSuite E2E Junk

on:
  pull_request:
    branches: [ "main" ]

jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    steps:
      - uses: kyma-project/lifecycle-manager/.github/actions/wait-for-image-build@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: pull-runtime-watcher-img-build
