name: TestSuite E2E Junk

on:
  pull_request:
    branches: [ "main" ]

jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done..."
      # - uses: kyma-project/lifecycle-manager/.github/actions/wait-for-image-build@main
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     statusName: pull-runtime-watcher-img-build

  e2e-integration:
    name: E2E
    needs: wait-for-image-build  
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout runtime-watcher
        uses: actions/checkout@v4

      - name: Checkout lifecycle-manager
        uses: actions/checkout@v4
        with:
          repository: kyma-project/lifecycle-manager
          path: lifecycle-manager

      - name: Checkout template-operator
        uses: actions/checkout@v4
        with:
          repository: kyma-project/template-operator
          path: template-operator

      - name: Get configuration
        uses: kyma-project/lifecycle-manager/.github/actions/get-configuration@main
        id: configuration
  
      - name: Setup tools
        uses: kyma-project/lifecycle-manager/.github/actions/setup-tools@main
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          istio_version: ${{ steps.configuration.outputs.istio_version }}
          k3d_version: ${{ steps.configuration.outputs.k3d_version }}
          go-version-file: runtime-watcher/go.mod
          cache-dependency-path: runtime-watcher/go.sum

      - name: Setup test clusters
        uses: kyma-project/lifecycle-manager/.github/actions/setup-test-clusters@main
        with:
          k8s_version: ${{ steps.configuration.outputs.k8s_version }}
          cert_manager_version: ${{ steps.configuration.outputs.cert_manager_version }}
